services:
  # PostgreSQL数据库
  postgres:
    image: postgres:14-alpine
    container_name: card-battle-postgres
    environment:
      POSTGRES_DB: card_battle_arena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - card-battle-network

  # Redis缓存和会话存储
  redis:
    image: redis:6-alpine
    container_name: card-battle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - card-battle-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  card-battle-network:
    driver: bridge